name: release
on: [push, pull_request]
jobs:

  # test is the usual merge-blocking CI pipeline responsible for testing the code
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Format Unix
        run: test -z $(go fmt ./...)
      - name: Test
        run: go test ./...


  # release is responsible for building and releases all artifacts when a new tag gets created.
  release:
    permissions:
      id-token: write # id-token write permission is necessary for accessing the GitHub OIDC workload identity token
      contents: write # contents write permission is necessary for creating the changelog and publishing it on the GitHub release page
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        # install cosign pulls cosign version v1.6.0 and installs it in our build environment
      - name: install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.6.0'
        # this step installs Syft for generating SPDX compatible SBOM documents
      - uses: anchore/sbom-action/download-syft@v0.7.0
        # this action is responsible for downloading, installing and executing GoReleaser.
        # Checkout the GoReleaser config in .goreleaser.yml for more information
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 'v1.6.3'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1
